title: Daniel Jörgens
description: Postdoc @ Krembil Research Institute, University Health Network, Toronto

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

github:
  repository_url: http://github.com/djoerch

hodaielab:
  homepage: http://hodaielab.com
  github: http://github.com/hodaielab

include: ['_pages']
